### ISSUE TITLE
:time_zone_not_found is ambiguous 

### ISSUE THREAD

**Issue by lguminski** [kimlai/tz_world#23]
`TzWorld.timezone_at` returns `{:error, :time_zone_not_found}` on two occasions:
1. when no timezone data is installed
2. when the location points to the middle of the ocean

It would be nice to have two different errors, because currently it is not possible to determine the actual cause.

**Comment by kipcole9** [comment]
@lguminski thanks for the report, I'll work on that over the next few hours and see if I can disambiguate the error message.

**Comment by kipcole9** [comment]
Hmmmm, on my testing, when there is no timezone data installed, I get the return `{:error, :enoent}`:
```elixir
iex> TzWorld.Backend.DetsWithIndexCache.start_link
{:ok, #PID<0.235.0>}
iex> TzWorld.timezone_at {0.0,0.0}                
{:error, :enoent}
```
Can you let me know which `TzWorld.Backend` you are using?  And if you have an example I can use to test that would be very helpful.

I did uncover a bug in the `TzWorld.Backend.Dets` module when there is no timezone data (now fixed) but I'm hoping thats not the backend you are using.

**Comment by kipcole9** [comment]
Another thought I'd appreciate is whether or not there should be an option to use the geo data that *includes* oceans.  Understandably its a larger data set, but not actually by that much (45.1Mb zipped versus 41.4Mb zipped). 

Thoughts?

**Comment by lguminski** [comment]
@kipcole9 no. I am not using `Dets`. I am using `DetsWithIndexCache` and it behaves exactly like the example at the bottom of the README.md file
```elixir
iex> TzWorld.timezone_at(%Geo.Point{coordinates: {1.3, 65.62}})
{:error, :time_zone_not_found}
```

Wikipedia says that there is a timezone even in the middle of the ocean. So perhaps instead or returning an error, the library should fallback to a generic string e.g. "Etc/GMT+1". And then `:time_zone_not_found` would appear only if there is no data installed, which would solve this issue. 

![wiki](https://upload.wikimedia.org/wikipedia/commons/8/88/World_Time_Zones_Map.png)

**Comment by kipcole9** [comment]
Ah, understood. I mistook your comment to refer to there was no downloaded data. I now understand you to mean when there is no data for the geo area in question (like the oceans).

Since the only operation I can perform is to find whether a given point is contained within a timezone polygon or not, its not possible to disambiguate the difference between "there is no timezone for this point" and "there is no data to decide if there is no timezone or not".

I'm just finishing up code to allow optionally using the geojson data that includes the oceans. I think that will be the best way to return the result you need since then we have global coverage and the return result in unambiguous.

Thanks for the additional information, very helpful to work out what to do next.

**Comment by kipcole9** [comment]
On my development machine:
```bash
kip@Kips-iMac-Pro tz_world % mix tz_world.update --include_oceans
06:40:21.732 [info]  [TzWorld] No timezone geo data installed. Installing the latest release 2021c.
```
Then resolving the point in your example:
```elixir
iex> TzWorld.timezone_at(%Geo.Point{coordinates: {1.3, 65.62}})
{:ok, "Etc/GMT"}
```

I just need to add some tests and also keep the state of whether updating should include oceans or not.  I'll push the current commit so you can try it out as a GitHub dependency since feedback would definitely be welcome.

**Comment by lguminski** [comment]
> Since the only operation I can perform is to find whether a given point is contained within a timezone polygon or not, its not possible to disambiguate the difference between "there is no timezone for this point" and "there is no data to decide if there is no timezone or not".

there is another solution. You don't need to have ocean data. You could simply use there original set, and if there is no poligon there that describes the location, calculate it simply based on longitude https://shapingminds.in/how-to-calculate-time-using-longitudes/

**Comment by lguminski** [comment]
@kipcole9 
the algorithm would be
1. find poligon in timezone data
2. if no poligon found return "Etc/GMT+{time_shift}" where `time_shift=round(longitude/15)`

(if time_shift == 0 ignore the suffix)

**Comment by kipcole9** [comment]
Its a good proposal but I'm reluctant to return values calculated this way as being "definitive".  The meanderings of the [International Date Line](https://www.timeanddate.com/time/dateline.html) don't given me confidence that the calculated timezone would be appropriate in all cases.

I'm happy to add a `TzWorld.calculated_timezone/1` function that does as you propose. That could be called if the result of `TzWorld.timezone_at/1` returns an error tuple.

That way you can either/or use the timezone data that includes oceans, or calculate the presumed timezone from the longitude.

Thoughts?

**Comment by lguminski** [comment]
> I'm happy to add a TzWorld.calculated_timezone/1 function that does as you propose. That could be called if the result of TzWorld.timezone_at/1 returns an error tuple. 

but this way we come back to the original problem. Currently the same error tuple is returned when "no data exists" and "data exists but no polygon matches". And the `TzWorld.calculated_timezone` would need to be called only for the second case.

**Comment by lguminski** [comment]
I think the `--include_oceans` is good enough. it is only 10% increase in size

**Comment by kipcole9** [comment]
> Currently the same error tuple is returned when "no data exists" and "data exists but no polygon matches"
Thats because as far as the code is concerned there is no difference (and no way to identify the difference).

I will push ahead to get the `--include_oceans` version out by end of my day (its morning here).

**Comment by lguminski** [comment]
@kipcole9 thanks a lot!

**Comment by kipcole9** [comment]
I've published [tz_world version 1.2.0](https://hex.pm/packages/tz_world/1.2.0) with the following changelog entry:

### Bug Fixes

* Fix `TzWorld.Backend.Dets` to not raise an exception if there is no timezone data available.

### Enhancements

* Adds options to `mix tzworld.update` mix task:
  * `--include_oceans` will download a 10% larger geojson data set that covers the worlds oceans
  * `--force` will force a data update, even if the data is the latest release. This can be used
    to switch between data that includes oceans and that which does not.
  * Thanks to @lguminski for the feedback and suggestion.

Let me know how it goes and if you spot any other issues?  Thanks for the collaboration, it push the library along in a good way.

**Comment by lguminski** [comment]
Thanks @kipcole9 . I think it would be good if Readme.md mentioned the new options.

**Comment by kipcole9** [comment]
Good call, thanks for the prompt. Done and published a docs update.

**Comment by kipcole9** [comment]
Just checking to see if everything is working as you expected?  Let me know if there's anything else you think is missing?

**Comment by lguminski** [comment]
Everything works. Thanks!
