### ISSUE TITLE
should :wx dependency be required?

### ISSUE THREAD

**Issue by mayel** [kimlai/tz_world#43]
This is causing me issues when trying to `mix release` in a docker that doesn't have or need wx

**Comment by kipcole9** [comment]
I didn't reaklise that `:extra_applications` propagated to consuming apps. You're right, it shouldn't be a hard requirement.  I'll work out a way to add it only if it's present. I assume that's your primary issue - `wx` isn't compiled into your production runtime?

**Comment by mayel** [comment]
That's right, I got `(Mix) Could not find application :wx` when running `mix release` after upgrading tz_world (in a docker build using hexpm's latest alpine-based image).

**Comment by kipcole9** [comment]
I've pushed a commit to have `:wx` and `:observer` included in `:extra_applications` only if they exist in the runtime. Would you consider given it a spin before I release?  Configure with `{:tz_world, github: "kipcole9/tz_world"}`.

**Comment by mayel** [comment]
that worked 👍

**Comment by kipcole9** [comment]
Phew, glad to hear it. I’ll publish a release in a few hours (2am in my current tz)Sent from my iPhoneOn 21 Oct 2024, at 01:37, Mayel de Borniol ***@***.***> wrote:﻿
that worked 👍

**Comment by kipcole9** [comment]
I've published [tz_world version 1.4.1](https://hex.pm/packages/tz_world/1.4.1) with he following changelog entry:

### Bug Fixes

* Don't include `:wx` and `:observer` in `:extra_applications` since this propogates and `:wx` may not be compiled in the target runtime. Thanks to @mayel for the report. Fixes #43.
